[tool.poetry]
name = "element"
version = "0.1.0"
description = "Elemental Discord API Wrapper"
authors = ["VincentRPS <vincentbusiness55@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8.1"
discord-typings = "^0.5.0"
colorlog = "^6.6.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"
mypy = "^0.961"
pyright = "^1.1.257"
types-orjson = "^3.6.2"
flake8 = "^4.0.1"
flake8-functions = "^0.0.7"
flake8-if-statements = "^0.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true
check_untyped_defs = true
incremental = true
namespace_packages = true
no_implicit_optional = true
pretty = true
python_version = "3.10"
show_column_numbers = true
show_error_codes = true
show_error_context = true
allow_untyped_globals = false
allow_redefinition = true
disallow_untyped_decorators = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.black]
skip-string-normalization = true

[tool.isort]
profile = 'black'

[tool.pyright]
strict = true
